# Generated by Django 4.2.5 on 2023-09-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='categoryz',
            new_name='category',
        ),
    ]
